### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Homosanians** [robertsLando/MongoDB-OrangePI#1]
I tried to do the same but with mongodb 3.6 and get this error:
root@orangepipc:/home/alex/install/mongodb-src-r3.6.8/src/third_party# scons mongo mongod -j4 --disable-warnings-as-errors --wiredtiger=off --mmapv1=on --warn=no-all

> scons: *** No SConstruct file found.
> File "/usr/lib/scons/SCons/Script/Main.py", line 924, in _main

**Comment by Homosanians** [comment]
i ran it from mongodb-src-r3.6.8/src, instead of mongodb-src-r3.6.8/src/third_party
but there's a new error

```
Checking for mongoc_get_major_version() in C library mongoc-1.0... no
EnvironmentError: No module named pkg_resources:
  File "/home/alex/install/mongodb-src-r3.6.8/SConstruct", line 3128:
    env.Tool('icecream')
  File "/usr/lib/scons/SCons/Environment.py", line 1788:
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 118:
    module = self._tool_module()
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 153:
    raise SCons.Errors.EnvironmentError(e)
```

**Comment by robertsLando** [comment]
Have you tried this? 
https://stackoverflow.com/questions/17182799/scons-no-sconstruct-file-found

If still not working I need to see also your previous commands

**Comment by robertsLando** [comment]
I think you may have missed the step for the resources fetch. 

Anyway, I really suggest you to use the precompiled version I provide here, It has been so hard to find a way to make mongo work and there are lot things that can go wrong in build process with newer versions. 

If you can build mongo 3.6 please submit a pull request with the binaries (better if in a separate folder named with the version "3.6" so everyone else can use them without building 😊

**Comment by Homosanians** [comment]
Ok. :з
I'll try
